Client start
F1int0m/WebChamber pull request #14
Opened 2022-11-29 03:51 UTC by Beck-Rollyhug

написан cra и навигация со страницами

2022-11-29 05:42 UTC, F1int0m requested changes

2022-11-29 05:42 UTC, F1int0m commented on .env
> +VK_CLIENT_SECRET=X5Ha1xlZ7UgpLPTOVdTa
Надо было не удалять файлик, а скопировать его себе и в гит не заносить(хотя он есть в гитигноре и не должен был попасть сюда)

2022-11-29 05:42 UTC, F1int0m commented on README.md
> +Docker run: docker run -it --rm -v ${PWD}:/frontend -v /frontend/node_modules -p 3000:3000 -e CHOKIDAR_USEPOLLING=true frontend:dev
Вот этого всего тут не нужно, потому что это под капотом делает docker-compose, который мы используем. Это все нужно описать там, если оно нужно(я вот не уверен, что нужно  с флагами -it запускать контейнер)

2022-11-29 05:42 UTC, F1int0m commented on frontend/Dockerfile
> +CMD ["npm", "start"]
Это можешь просто резолвить.

Но по хорошему нужно либо убрать это тут и оставить в запуске, либо убрать это в запуске контейнера и убрать тут

2022-11-29 05:42 UTC, F1int0m commented on frontend/package.json
> +  "proxy": "http://localhost:80",
А вот эту штуку никак нельзя в какой-нибудь конфиг вынести или из окружения брать?

Я просто не уверен, что тут оно нужно в таком виде, но потом когда нормально фронт будем собирать проверим работает ли оно как нужно

2022-11-29 05:42 UTC, F1int0m commented on frontend/public/index.html
> +      content="Web site created using create-react-app"
Может поудалять лишнее, которое явно тупо заглушка? Или просто на свое переписать?

2022-11-29 05:42 UTC, F1int0m commented on frontend/src/App.test.js
> +test('renders learn react link', () => {
Нам правда нужен такой тест?)

2022-11-29 05:42 UTC, F1int0m commented on frontend/src/auth/fetchOAuth.js
> +export async function FetchOAuth() {
Она же нигде не используется? Давай удалим?

2022-11-29 05:42 UTC, F1int0m commented on frontend/src/content/pages/public/Login.jsx
> +        const nt = FetchToken()
А оно точно так должно работать? Функция же ничего не возвращает, какой смысл ее результат тогда где-то сохранять?

2022-11-29 05:42 UTC, F1int0m commented on frontend/src/content/pages/system/TokenSetup.jsx
> +            <h3>Current token: {token}</h3>
Выглядит очень страшно(показывать токен юзеру). Это остатки дебага или так нужно?

2022-11-29 05:42 UTC, F1int0m commented on frontend/src/env.js
> +export const ROOT_URL = '/'
Давай это все нормально сделаем через переменные окружения?

https://create-react-app.dev/docs/adding-custom-environment-variables

Сделать можно также, как сделаны секреты на уровне всего проекта (файлики .env и .env.example)

2022-11-29 06:44 UTC, F1int0m requested changes

2022-11-29 06:44 UTC, F1int0m commented on .gitignore
> +frontend/.env.preparation
Верни еще эту строку назад, потому что из-за этого сломалась вся система с защитой секретов от пуша в гит

2022-12-02 07:36 UTC, F1int0m requested changes

2022-12-02 07:36 UTC, F1int0m commented on frontend/src/App.js
> +// import {useSelector} from "react-redux";
Раз оно не используется, то можно убрать же

2022-12-02 07:36 UTC, F1int0m commented on frontend/src/auth/setOAuthToken.js
> +    body: JSON.stringify({
А может есть уже готовая либа для этого? Руками это грустно будет разбирать

2022-12-07 11:30 UTC, Beck-Rollyhug commented
ок

2022-12-07 12:12 UTC, F1int0m requested changes

2022-12-07 12:12 UTC, F1int0m commented on frontend/src/env.js
> +export const SERVER_HOST = 'http://localhost:80/';
Почему ты самые бесполезные переменные вынес в конфиг(они там совсем не нужны так то), а единственную важную захардкодил?

2022-12-12 03:09 UTC, F1int0m approved these changes

2022-12-12 03:16 UTC, merged