Client pages view setup
F1int0m/WebChamber pull request #26
Opened 2022-12-18 06:25 UTC by Beck-Rollyhug

первый вариант визуала основных компонентов. Тыкательный профиль и компонент с постами - без ручек, добавил иконки в компоненты и на вкладку браузера

2022-12-18 06:34 UTC, F1int0m requested changes

2022-12-18 06:34 UTC, F1int0m commented on frontend/src/auth/setOAuthToken.js
> -    console.log('Go to auth on url=' + AUTH_URL)
Зачем удалил? Я специально это тут написал, чтобы было понятно куда и как что уходит

2022-12-18 06:34 UTC, F1int0m commented on frontend/src/auth/setOAuthToken.js
> +    */
А вот этот весь коммент я тоже специально удалил, потому что в этом методе он не актуален, а другие я бы хотел, чтобы ты через клиента сделал

2022-12-18 06:34 UTC, F1int0m commented on frontend/src/system/env.js
> +export const SETTINGS_URL = process.env.REACT_APP_SETTINGS_URL;
Ну зачем? Я же тебе говорил, что эти штуки или не меняются, или меняются, но важно это только тебе тут. Оставь захардкоженые, чтобы не тащить лишнего в конфиг

2022-12-18 06:34 UTC, F1int0m commented on frontend/src/view/components/navigation/ChamberHeader.jsx
> +                    <NavLink to={ROOT_URL + CHAMBER_URL + 'people'}>Люди</NavLink>
Эти штуки ты вроде в конфиг же выносил

2023-01-20 13:56 UTC, Beck-Rollyhug reviewed
ok

2023-01-20 14:04 UTC, F1int0m approved these changes

2023-01-20 14:05 UTC, merged